name: CI - Tauri

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check frontend
      run: npm run lint
      
    - name: Check Rust formatting
      run: cargo fmt --all -- --check
      working-directory: src-tauri
      
    - name: Run Rust clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: src-tauri
      
    - name: Run Rust tests
      run: cargo test
      working-directory: src-tauri
      
    - name: Build frontend
      run: npm run build
      
    - name: Build Tauri app (test)
      run: cargo tauri build --debug
      working-directory: src-tauri